version: '3.3'

services:

  maven:
    build: maven/
    volumes:
      - static:/usr/local/boxfuse-sample-java-war-hello/target/hello-1.0.war

  tomcat:
    image: tomcat:9.0.0.M15-jre8-alpine
    ports:
      - "80:8080"
    volumes:
      - static:/opt/tomcat/webapps

volumes:
  static:

